// initial map options, abeling pan/zoom and centering the map at KY
var options = {
    center: [37.9, -85],
    zoom: 7,
    minZoom: 3,
    maxZoom: 20,
    dragging: true,
    zoomControl: true
}

// create Leaflet map and apply options
var map = L.map('map', options);

// load map tiles and add to map 
var tiles = L.tileLayer('http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="http://cartodb.com/attributions">CartoDB</a>',
    subdomains: 'abcd',
});
debugger
map.addLayer(tiles);

// declare global variables
// mapped attribute
var dataLayer,
    ATTRIBUTE = '2000';

// AJAX requests to load data files
$.getJSON("ky-counties.json", function(counties) {
    // Papa.parse organizes and read the CSV file properly
    Papa.parse('ky-unemployment-data.csv', {
        download: true,
        header: true,
        complete: function(data) {
            //calls a function to update the data
            processData(counties, data);
        }
    }); // end of Papa.parse() 
});  // end of $.getJSON()

// function to process/bind data

function processData(counties, data) {
    // first loop though the counties
    for (var county in counties.features) {

        var props = counties.features[county].properties;
        //then loop through the data
        for(var datum in data.data) {
            //this binds the data to the properties of the layer
            if(props.COUNTY_FIP == data.data[datum].CNTY) {
                counties.features[county].properties = data.data[datum]; 
                break;
            }
        }
    }
    drawMap(counties);
}

// function to draw the map

function drawMap(counties) {
    
    //this draw the geometries on the basemap
    dataLayer = L.geoJson(counties, {
        style: function(feature) {
            // style counties with initial default path options
            return {
                    color: '#ffffff',
                    weight: 2,
                    fillOpacity: 0.8,
                    fillColor: 'rgba(189, 0, 38, 0)'
            }
        }          
    }).addTo(map);
    //calls all the other functions to complement the map and legends
    drawInfo();
    createSliderUI();
    drawLegend();
    updateMap();
    // this shows/hide the info panel when you moue over/mouse out on the layer
    dataLayer.on('mouseover', function() {
        $(".info").show();
    });
    dataLayer.on('mouseout', function() {
        $(".info").hide();
    });
}
// function to update the map

function updateMap() {
    //this get the class breaks for the initial attributes
    var breaks = getClassBreaks();
    dataLayer.eachLayer(function(layer) {
        // this sets a new style to the layer based on the brakes generated by the function getBreaks and associated to getColor
        layer.setStyle({
            fillColor: getColor(layer.feature.properties[ATTRIBUTE], breaks)
        });
        //This binds a popup to the click event
        layer.bindPopup("<b>"+layer.feature.properties["NAME"]+" County</b><br>" + ATTRIBUTE + ": " + layer.feature.properties[ATTRIBUTE] + "%");
        // this changes the boundary color when you mouse over the county
        layer.on('mouseover', function() {
            updateInfo(this); 
            layer.setStyle({color: '#000'}).bringToFront();
        });
        layer.on('mouseout', function() {
            layer.setStyle({color: '#dddddd'});
        });
    });
    updateLegend(breaks);
}
// function get the class breaks   
//this function creates the class breaks based on the values chosen by the user using the slider
function getClassBreaks(){
    var values = [];
    var value;
    dataLayer.eachLayer(function(layer) {
        value = layer.feature.properties[ATTRIBUTE];
        values.push(Number(value));
    });
    // using statistics to determine breaks in each 20%
    var breaks = ss.quantile(values, [0, 0.2, 0.4, 0.6, 0.8, 1]);
    return breaks;
}

// function to get the color value
//function to associate the breaks to a color
function getColor(d, breaks) {
    //function receiver a single normalyzed data attribute
    if (d <= breaks[1]) {
        return '#ffffb2';
    } else if (d <= breaks[2]) {
        return '#fecc5c';
    } else if (d <= breaks[3]) {
        return '#fd8d3c';
    } else if (d <= breaks[4]) {
        return '#f03b20';
    } else if (d <= breaks[5]) {
        return '#bd0026';
    }
}

// function to draw the legend

function drawLegend() {
    //this function draws a legend on the map
    var legend = L.control({position: 'bottomright'});
    legend.onAdd = function(map) {
        var div = L.DomUtil.create('div', 'legend');
        return div;
    }
    legend.addTo(map);
}

// function to update the legend
// this function updates the legend with some content created by the other functions
function updateLegend(breaks) {
    var legend = $('.legend').html("<h3>% Unemployment: " + ATTRIBUTE + "</h3><ul>"); 
    for (var i = 0; i < breaks.length-1; i++) {
        var color = getColor(breaks[i + 1], breaks);
        legend.append('<li><span style="background:' + color + '"></span> ' +
            (breaks[i]).toLocaleString() + ' &mdash; ' + 
            (breaks[i + 1]).toLocaleString() + '</li>');
    }
    legend.append("</ul>");
}

// function to create the range slider
// this function introduces the slider on the map
function createSliderUI() {
    var sliderControl = L.control({ position: 'bottomleft'} );
    sliderControl.onAdd = function(map) {
        var slider = L.DomUtil.get("ui-controls");
            L.DomEvent.addListener(slider, 'mousedown', function(e) { 
                L.DomEvent.stopPropagation(e); 
            });
        return slider;
    }
    sliderControl.addTo(map);
    //and uses a JQuery object to bind the value slided to the ATTRIBUTE global variable created on the begining
    $(".year-slider").on('input change', function() {
        ATTRIBUTE = $(this).val();
        updateMap();
    });
}

// function to draw the info panel
//this function draws a info panel on the map
function drawInfo() {
    var info = L.control({position: 'topright'});
        info.onAdd = function(map) {
            var div = L.DomUtil.create('div', 'info');
            return div;  
        }
    info.addTo(map);
    //the info panes is initialy hided and popsup when you mouse over the KY state
    $(".info").hide();
}

// function to update the info panel
//this function binds some hardcoded information to the info panel
function updateInfo(layer) {
    var props = layer.feature.properties;
    var html = "<b>" + props['NAME'] + " County </b><br><h3>2000: " + props[2000] + " <br>2001: " + props[2001] + " <br>2002: " + props[2002] + " <br>2003: " + props[2003] + " <br>2004: " + props[2004] + " <br>2005: " + props[2005] + " <br>2006: " + props[2006] + " <br>2007: " + props[2007] + " <br>2008: " + props[2008] + " <br>2009: " + props[2009] + " <br>2010: " + props[2010] + " <br>2011: " + props[2011] + " <br>2012: " + props[2012] + " <br>2013: " + props[2013];
    $(".info").html(html);
}